---
- name: check ja_JP.UTF-8 locale
  shell: locale -a | grep -i ja_JP.UTF-*8
  register: result
  failed_when: result.rc not in [0, 1]

- name: generate ja_JP.UTF-8 locale
  command: /usr/sbin/locale-gen ja_JP.UTF-8
  when: result.rc == 1
